name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update stable && rustup default stable

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
